<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>8741e30d-1bae-43bf-8e19-ae4ae7535350</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.6" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="10.0.6" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.6" />
  </ItemGroup>

</Project>